project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "!*.md"
    - "!README.md"
    - "!LICENSE.md"
  resources:
    - "thoughts/*.html"
    - "thoughts/*.xml"
    - "thoughts/*.css"
    - "thoughts/img/*"

description-meta: "A blog exploring infectious diseases, statistics, epidemiology, and data science."

website:
  title: "Insufficient Statistics"
  description : "A blog exploring infectious diseases, statistics, epidemiology, and data science."
  favicon: sirs.png
  site-url: https://michaeldewittjr.com
  repo-url: https://github.com/medewitt/quarto-blog
  open-graph: true
  twitter-card:
    creator: "@medewittjr"
    card-style: summary_large_image
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: home
      - text: "contact me"
        menu:
        - icon: mastodon
          href: https://mastodon.social/@Medewitt
          text: "@Medewitt"
        - icon: github
          href: https://github.com/medewitt
          text: "medewitt"
        - icon: linkedin
          href: https://www.linkedin.com/in/michael-dewitt-jr/
          text: michael-dewitt-jr
        - icon: lightbulb
          href: https://orcid.org/0000-0001-8940-1967
          text: "ORCID"
        - icon: envelope
          href: mailto:me.dewitt.jr@gmail.com
          text: "me.dewitt.jr@gmail.com"
      - text: "blogs"
        menu:
        - programming.qmd
        - posts.qmd
        - text: "substack"
          href: https://michaeldewittjr.substack.com/
      - presentations.qmd
      - text: teaching
        menu:
        - text: "Introduction to R"
          href: https://medewitt.github.io/introduction_to_r/index.html
        - text: "Advanced Analysis in R"
          href: https://medewitt.github.io/advanced_analysis_in_r/index.html
        - text: "Reading Notes"
          href: https://www.dewittlab.com
        - text: "Virus Dynamics in R"
          href: https://medewitt.github.io/virusdynamics/
        - text: "SARS2 Fitness Tracker"
          href: https://medewitt.github.io/sars2-fitness-tracker/
      - text: "newsfeed"
        href: https://medewitt.github.io/news/index.html
      - about.qmd
      - icon: rss
        href: programming.xml

format:
  html:
    theme: [cosmo, michael.scss]
    css: styles.css
    toc: true

freeze: true