---
title: "selected works"
---

Working in private organizations limits what I can show publicly, but here are some publically available things that I can show.

## publications

* **DeWitt M** , Wierzba TF. Automatic Case Cluster Detection Using Hospital Electronic Health Record Data. Biology Methods and Protocols. Published online March 15, 2023:bpad004. <doi:10.1093/biomethods/bpad004>

* **DeWitt ME**, Tjaden AH, Herrington D, et al. COVID-19 Symptoms by Variant Period in the North Carolina COVID-19 Community Research Partnership, North Carolina, USA - Volume 29, Number 1—January 2023 - Emerging Infectious Diseases journal - CDC. doi:10.3201/eid2901.221111

* Stone, T. J., **DeWitt, M.**, Johnson, J. W., Beardsley, J. R., Munawar, I., Palavecino, E., Luther, V. P., Ohl, C. A., \& Williamson, J. C. (2023). Analysis of infections among patients with historical culture positive for extended-spectrum beta-lactamase (ESBL)–producing Escherichia coli or Klebsiella pneumoniae: Is ESBL-targeted therapy always needed? Antimicrobial Stewardship \& Healthcare Epidemiology, 3(1), e47. <https://doi.org/10.1017/ash.2022.363>

* Polk, C., Sampson, M., Fairman, R. T., **DeWitt, M. E.**, Leonard, M., Neelakanta, A., Davidson, L., Roshdy, D., Branner, C., McCurdy, L., Ludden, T., Tapp, H., \& Passaretti, C. (2023). Evaluation of a health system’s implementation of a monkeypox care model under the RE-AIM framework. Therapeutic Advances in Infectious Disease, 10, 20499361231158464. <https://doi.org/10.1177/20499361231158463>

* **DeWitt, M. E.**, Herrington, D. M., \& Sanders, J. W. (2023). Venous or Arterial Thrombosis in COVID-19 Cases in the North Carolina COVID-19 Community Research Partnership (NC-CCRP). Research and Practice in Thrombosis and Haemostasis, 100080. <https://doi.org/10.1016/j.rpth.2023.100080>

* Semelka, C. T., **DeWitt, M. E.**, Blevins, M. W., Holbrook, B. C., Sanders, J. W., \& Alexander-Miller, M. A. (2023). Frailty impacts immune responses to Moderna COVID-19 mRNA vaccine in older adults. Immunity \& Ageing, 20(1), 4. <https://doi.org/10.1186/s12979-023-00327-x>

* **DeWitt ME**, Polk C, Williamson J, Shetty AK, Passaretti CL, McNeil CJ, et al. Global monkeypox case hospitalisation rates: A rapid systematic review and meta-analysis. EClinicalMedicine 2022;54:101710. <https://doi.org/10.1016/j.eclinm.2022.101710>.
      
* Sampson MM, Polk CM, Fairman RT, **DeWitt ME**, Leonard MK, Davidson L, et al. Monkeypox testing delays: The need for drastic expansion of education and testing for monkeypox virus. Infect Control Hosp Epidemiol 2022:1–2. <https://doi.org/10.1017/ice.2022.237>.

* C. T. Semelka, **M. E. DeWitt**, K. E. Callahan, D. M. Herrington, M. A. Alexander-Miller, J. O. Yukich, I. Munawar, L. H. McCurdy, M. A. Gibbs, W. S. Weintraub and J. W. Sanders. “Frailty and COVID-19 mRNA Vaccine Antibody Response in The COVID-19 Community Research Partnership.” J Gerontol A Biol Sci Med Sci; DOI: <https://doi.org/10.1093/gerona/glac095>

* **Michael E. DeWitt**, Christopher Scheib, Morgan Jones and Pamela Cowin North Carolina Medical Journal July 2021, 82 (4) 284-286; DOI: <https://doi.org/10.18043/ncm.82.4.284>

* Summers, Phillip, and **Michael DeWitt**. “Analysis of the Winston-Salem Public Transit System.” Virginia Policy Review, October 31, 2018. <http://www.virginiapolicyreview.org/1/post/2018/10/analysis-of-the-winston-salem-public-transit-system.html>.
    

## software

Sam Abbott, Joel Hellewell, Katharine Sherratt, Katelyn Gostic, Joe Hickson, Hamada S. Badr, Michael
DeWitt, Robin Thompson, EpiForecasts, and Sebastian Funk (2020). EpiNow2: Estimate Real-Time
Case Counts and Time-Varying Epidemiological Parameters, DOI: 10.5281/zenodo.3957489

Sam Abbott, Nikos Bosse, Joel Hellewell, Katharine Sherratt, James Munday, Robin Thompson, Aurelien Chateigner, Sylvain Mareschal, Andrea Rau, Nathalie Vialaneix, Michael DeWitt and Sebastian Funk (2020). EpiSoon: Forecast Cases Using Reproduction Numbers. R package version 0.3.0.

DeWitt et al., (2019). tidyqwi: A Tidy Approach to Accessing The US Census Bureau's Quarterly Workforce Indicators. Journal of Open Source Software, 4(38), 1462, <https://doi.org/10.21105/joss.01462>
  
Bruno Castanho Silva and Michael DeWitt (2019). SCtools: Extensions for Synthetic Controls Analysis. R package version 0.3.0. <https://CRAN.R-project.org/package=SCtools>
  
## Working Papers

DeWitt ME, Sampson MM, Fairman RT, McNeil CJ, Polk CM, Passaretti CL, et al. Estimated Monkeypox Susceptible MSM Population in North Carolina 2022:2022.07.21.22277860. https://doi.org/10.1101/2022.07.21.22277860.

DeWitt, Michael E. “Rapid Impact Analysis of B 1.1.7 Variant on the Spread of SARS-CoV-2 in North Carolina.” MedRxiv, February 9, 2021, 2021.02.07.21251291. <https://doi.org/10.1101/2021.02.07.21251291>.

DeWitt, Michael E. “Automatic Contact Tracing for Outbreak Detection Using Hospital Electronic Medical Record Data.” MedRxiv, September 13, 2020, 2020.09.08.20190876. <https://doi.org/10.1101/2020.09.08.20190876>.

  
## technical papers

* [**Office of Institutional Research Survey Methodology**](https://prod.wp.cdn.aws.wfu.edu/sites/202/2018/05/oir_survey_methodology.pdf), _Wake Forest University_, May 2018


## public comment

This section represents any public analysis that has been presented to any public bodies.

* [**Winston-Salem Public Transit Analysis**](https://michaeldewittjr.com/bus_analysis/) by Michael DeWitt, Phillip Summers, Jeff Bloomfield, Keena Moore, Megan Irby, _Winston-Salem City Council_, September 2018

## applications

This sections represents public facing applications.

* [**Winston-Salem Police Department Tracker**](https://mdewitt.shinyapps.io/wspd_scanner/) October 2018

* [**Algorithmic Bias Simulator**](https://mdewitt.shinyapps.io/bias_simulation/) February 2019

## presentations

This is a non-exhaustive list of presentations that I have given.

* **Designing a Student Retention Model**,  _North Carolina Independent Colleges and Universities Institutional Research Directors Meeting_, December 2018

* **Does My Instructor Look Like Me: A Multi-Institution Look at Implicit Bias in Grading**,  _Southern Association for Institutional Research_, October 2018

* [**Comparing Two Groups: Effect Sizes**](https://docs.google.com/presentation/d/e/2PACX-1vTACUkOIFra4TqEvaQUCakpsYk7KgIRBdyo14hLJ798GiPb8Z4bY0YlgvcJoj1yoDc1_9wtUXqOKbii/pub?start=false&loop=false&delayms=3000),  _Wake Forest University Business Analytics Team_, September 2018

* [**Comparing Two Groups: T-Test**](docs/2018-08_BAI_t-test.pdf), _Wake Forest University Business Analytics Team_, August 2018

* [**Introduction to R**](https://github.com/medewitt/intro_to_r/blob/master/presentations/intro_presentation.pdf), _Wake Forest University Professional Development_, March 2018

* [**Overview of Distributions**](docs/2018-02_BAI_distributions.pdf), _Wake Forest University Business Analytics Team_, February 2018

* [**Measures of Central Tendency**](docs/2017-12_BAI_central_tendency.pdf), _Wake Forest University Business Analytics Team_, December 2017

* **Graphing Different Kinds of Data**, _Wake Forest University Business Analytics Team_, November 2017

## patents

[Procede d’identifier, gerer et réincorporer les produits complexes comme les produits valorises ](https://register.epo.org/application?number=EP19702385)(WO2019154657 - 2019-08-15, applied)

[Systeme d’identifier, gerer et reincorporer les produits complexes comme les produits valorises](https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2019154656)(WO2019154656 - 2019-08-15, applied)
