name: Update submodule

on:
  push:
    branches: [main,dev, ceg]
  schedule:
    - cron:  '10 13 * * *'
  repository_dispatch:
    types: [sample_push]
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v2
#      - uses: r-lib/actions/setup-r@v1
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: update
        run: just updatethoughts 
      - name: updatethoughts
        run: just thoughts 
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update the latest data" -a || echo "No changes to commit"
          git show --pretty=%gd --stat
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"

        
